# Generated by Django 3.0.7 on 2020-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('dt_cadastro', models.DateField(auto_now_add=True)),
                ('nm_aluno', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['matricula'],
            },
        ),
    ]
