# Generated by Django 3.0.7 on 2020-11-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20201104_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_rua', models.CharField(max_length=70)),
                ('nm_bairro', models.CharField(max_length=30)),
                ('nm_cidade', models.CharField(max_length=30)),
                ('nm_estado', models.CharField(max_length=20)),
            ],
        ),
    ]
