# Generated by Django 3.0.7 on 2020-11-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='fk_endereco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aluno.Endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nr_endereco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
