# Generated by Django 3.0.7 on 2020-11-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_auto_20201104_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_cidade', models.CharField(max_length=30)),
                ('nm_estado', models.CharField(max_length=20)),
                ('sg_estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='nm_cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='nm_estado',
        ),
        migrations.AddField(
            model_name='endereco',
            name='fk_cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aluno.Cidade'),
            preserve_default=False,
        ),
    ]
