# Generated by Django 3.0.7 on 2020-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_auto_20201104_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='nm_pais',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
