# Generated by Django 3.0.7 on 2020-11-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_cidade_nm_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=-1),
        ),
    ]
