# Generated by Django 3.0.7 on 2020-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_auto_20201104_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
    ]
