# Generated by Django 3.0.7 on 2020-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_auto_20201104_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='nm_cidade',
            field=models.CharField(max_length=30, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='nm_rua',
            field=models.CharField(max_length=70, verbose_name='Rua'),
        ),
    ]
